export const newsSources = {
  xAccounts: [
    { handle: '@AmitSegal', name: 'Amit Segal', role: 'Channel 12 political analyst, Ark Media contributor' },
    { handle: '@Nadav_Eyal', name: 'Nadav Eyal', role: 'Yediot Ahronot columnist, Ark Media contributor' },
    { handle: '@BarakRavid', name: 'Barak Ravid', role: 'Axios and Walla reporter' },
    { handle: '@havivrettiggur', name: 'Haviv Rettig Gur', role: 'Free Press analyst' },
    { handle: '@JoshKraushaar', name: 'Josh Kraushaar', role: 'Jewish Insider editor in chief' },
    { handle: '@benshapiro', name: 'Ben Shapiro', role: 'Daily Wire founder' },
    { handle: '@lahavharkov', name: 'Lahav Harkov', role: 'Jewish Insider Israel reporter' },
    { handle: '@shemeshmicha', name: 'Michael Shemesh', role: 'Kan political correspondent' },
    { handle: '@ranboker', name: 'Ran Boker', role: 'Ynet reporter' },
    { handle: '@BaruchYedid', name: 'Baruch Yedid', role: 'Channel 14 Arab affairs reporter' },
    { handle: '@AmichaiStein1', name: 'Amichai Stein', role: 'Kan diplomatic correspondent' },
    { handle: '@AnnaBarskiy', name: 'Anna Rayva-Barsky', role: 'Maariv political correspondent' },
    { handle: '@Doron_Kadosh', name: 'Doron Kadosh', role: 'Army Radio military correspondent' },
    { handle: '@inon_yttach', name: 'Yinon Shalom Yatach', role: 'i24 News military correspondent' },
    { handle: '@Osint613', name: 'Open Source Intel', role: '' },
  ],
  englishSites: [
    'Times of Israel + liveblog (most useful for developing stories)',
    'Wall Street Journal + liveblog',
    'New York Times',
    'Associated Press + liveblog',
    'Reuters',
    'Jerusalem Post + liveblog',
    'I24 News English',
    'Haaretz English + liveblog',
    'Al Jazeera English',
    'It\'s Noon in Israel – Amit Segal',
    'Between Us – Nadav Eyal',
    'Semafor',
    'Bloomberg',
  ],
  hebrewSites: [
    'Ynet + liveblog',
    'Israel Hayom + liveblog',
    'Kan + liveblog',
    'Maariv + liveblog',
    'Channel 14 + liveblog',
    'Calcalist + liveblog',
    'Walla + liveblog',
    'Haaretz',
    'Channel 12/Mako',
    'Globes',
    'Channel 13',
  ],
  analysisAndThinkTanks: [
    'Foundation for Defense of Democracies',
    'Free Press',
    'Jerusalem Institute for Strategy and Security',
    'Institute for National Security Studies',
    'Jewish Institute for National Security of America',
    'Misgav Institute',
    'Alma Center',
    'Tablet',
    'Commentary',
    'Atlantic',
    'Foreign Affairs',
  ],
};
